### ISSUE TITLE
Help: after I compile the problem

### ISSUE THREAD

**Issue by a3396616601** [JunkyBulgaria/WoWCircle-5.4.7#1]
Hello, brother, I need your help!
There are 74 compile time: warning in vs 2013

When running!
VMap support included. LineOfSight:1, getHeight:1, indoorCheck:1 PetLOS:1
VMap data directory is: data/vmaps
Map file 'data/maps/0000_43_31.map': does not exist!
Correct *.map files not found in path 'data/maps' or *.vmtree/*.vmtile files in 'data/vmaps'. Please place *.map/*.vmtree/*.vmtile files in appropriate directories or correct the DataDir value in the worldserver.conf file.
Thank you。
Also thanks to Google translate! Let's have a chance to communicate!
Thanks again

**Comment by FALL1N1** [comment]
i do not offer any support for this source code

**Comment by a3396616601** [comment]
Thank you。
