### ISSUE TITLE
Compile Core 

### ISSUE THREAD

**Issue by Apheleos** [JunkyBulgaria/WoWCircle-5.4.7#3]
Hi, thank for you share. 

Nevertheless, I encounter a few problems. I compiled the core in "debug" and "release" mode but the worldserver.exe closes directly. I also have several "warnings": 

* http://img4.hostingpics.net/pics/229045llllllll.png

Worldserver.exe weighs 20Mb, while in the repack it weighs 32Mb. 

I guess he did not compile everything. I also tried RelWithDeb but it's too long. I'm not the only one to be stuck, could you help us?

Thank you :)

**Comment by FALL1N1** [comment]
no, i can't

**Comment by Apheleos** [comment]
Ok, thx... but how did you compile it ?

**Comment by Artamedes** [comment]
by using a brain, it's not hard, learn to know what the fuck your doing

**Comment by thrallgamer** [comment]
Source Broken
